name: pantry
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_ai: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.5.0
  flutter_riverpod: ^3.0.3
  geolocator: ^13.0.1
  go_router: ^17.0.1
  google_sign_in: ^6.2.1
  google_mlkit_barcode_scanning: ^0.14.1
  google_mlkit_text_recognition: ^0.15.0
  google_maps_flutter: ^2.14.0
  http: ^1.2.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sign_in_with_apple: ^6.1.3
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
